### ISSUE TITLE
Do not pick or select date for time range analysis

### ISSUE THREAD

**Issue by haipn1983** [BuddyVolly/coverage_analysis#19]
I could not pick the date in the tool

**Comment by BuddyVolly** [comment]
Thanks Hai,
we'll look into that and fix it.

**Comment by BuddyVolly** [comment]
It should be solved, please let us know in case you have further issues. 
Thanks,
Andreas

**Comment by haipn1983** [comment]
Yes the tool is fixed, but this still problem with the tool: Forest Canopy
Disturbance Monitoring (FCDM Tool)
Best Regards


--------------------------------------------------------------------------
--------------------------------------------------------------------------

*Mr. Pham Ngoc HaiForest Inventory and Planning Institute (FIPI),*
Address: Vinh Quynh, Thanh Tri, Ha Noi
***@***.***,105.8462435,15.25z/data=!4m5!3m4!1s0x3135ad91822d5d3d:0xf0a271d48902c987!8m2!3d20.9299897!4d105.8462763>
Website: http://fipi.vn/
Mobile: 0902 09 16 90
Email: ***@***.***; ***@***.***,
Skype: ***@***.***



Vào Th 4, 8 thg 3, 2023 vào lúc 14:08 BuddyVolly ***@***.***>
đã viết:
