### ISSUE TITLE
change legend value color

### ISSUE THREAD

**Issue by yfinegold** [BuddyVolly/coverage_analysis#7]
Just a small suggestion. 

At the moment the legend value is black and the background box is grey, making it very difficult to see the value. Could you change the text color to white? That would make it readable :) 

Is this a sepal-ui issue? Because there's the same issue in other apps as well. 

![image](https://user-images.githubusercontent.com/5813936/122912203-5d402600-d358-11eb-820a-b9b482dc4617.png)

**Comment by BuddyVolly** [comment]
You are right. The issue for the app has already been solved, but it somehow does not update on Sepal. I will check and close the issue, once that's done. Sorry for the inconvenience

**Comment by BuddyVolly** [comment]
@12rambau this goes to you and sepal_ui, background issue

**Comment by 12rambau** [comment]
The new colorbar that will be available in sepal_ui 2.1.0. I kept the same method signature so you will have nothing to change (apart from setting a more meaningful title)

In SEPAL this summer ;-) 

<img width="893" alt="Capture d’écran 2021-07-30 à 11 42 26" src="https://user-images.githubusercontent.com/12596392/127634731-eb813174-54e6-4dfc-8115-aefece145a0c.png">

**Comment by BuddyVolly** [comment]
fixed
